# Generated by Django 2.2.4 on 2019-08-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='iddd',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='user_password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='user_profile',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='profile',
        ),
        migrations.AddField(
            model_name='signup',
            name='user_csrf',
            field=models.CharField(default='0000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='user_id',
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
